allowBuilds:
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
minimumReleaseAgeExclude:
  - pg-cloudflare@1.4.1
  - pg-connection-string@2.14.1
  - pg-protocol@1.16.1
  - pg@8.23.1
